---
title: "Bandit Analysis"
output: github_document
---

Read in the data and store it as a data frame

```{r setup, include=FALSE}

library(rhdf5)
library(tidyverse)
library(ggplot2)

```


```{r helper functions}
# Load helper functions
source("banditAnalysis.r")

```

```{r test stats functions}
# Generate a synthetic experiment with the function above

syntheticExperiment1 <- syntheticData(nTrials = 300,
                                      LeftBias=0.75,
                                      ProbBandicVec = setNames(c(0.8,0.8,0.8),c("AC>A","AB>A","BC>B")),
                                      modeProbVec = c(1,0,0), # LeftBias Opitmal Explorer
                                      timePerBandit = setNames(c(10,10,10,10,10,10),c("AC>A","AC>C","AB>A","AB>B","BC>B","BC>C")),
                                      RewardProbPerStation = setNames(c(1,0.5,0.25),c("A","B","C")))

syntheticStats1 <- mouseExpStats(syntheticExperiment1[[1]],syntheticExperiment1[[2]],"Synthetic Experiment Test 1")
```

```{r try varying left bias}

# Create 100 synthetic experiments and compute their stats and save it as a dataframe 
syntheticExperimentsLeftBias <- list()
for(i in 1:100){
    syntheticExperimentsTemp <- list()
    for(j in 1:40){	
        temp <- syntheticData(nTrials = 200,
                                LeftBias=i/100, # VARY THE LEFT BIAS
                                ProbBandicVec = setNames(c(0.5,0.5,0.5),c("AC>A","AB>A","BC>B")),
                                modeProbVec = c(1,0,0), # LeftBias Opitmal Explorer
                                timePerBandit = setNames(c(10,10,10,10,10,10),c("AC>A","AC>C","AB>A","AB>B","BC>B","BC>C")),
                                RewardProbPerStation = setNames(c(1,0.5,0.25),c("A","B","C")))
        syntheticExperimentsTemp[[j]] <- mouseExpStats(temp[[1]],temp[[2]],paste0("Synthetic Experiment ",i)) %>% unname()
    }
    # create a dataframe from the list of vectors and compute the column means, then add that to the list of experiments
    syntheticExperimentsLeftBias[[i]] <- do.call(rbind.data.frame, syntheticExperimentsTemp) %>% colMeans(na.rm=FALSE) %>% unlist()
}
# Create a dataframe from the list of experiments
syntheticExperimentsLeftBiasDF <- do.call(rbind.data.frame, syntheticExperimentsLeftBias) %>% readr::type_convert()
colnames(syntheticExperimentsLeftBiasDF) <- names(syntheticStats1)


```

```{r try going from from random to optimal strategy}

# Create 100 synthetic experiments and compute their stats and save it as a dataframe 
syntheticExperimentsOptimal <- list()
for(i in 1:100){
    syntheticExperimentsTemp <- list()
    for(j in 1:40){	
        temp <- syntheticData(nTrials = 200,
                                LeftBias=0.5, # Keep the left Bias Stable (random)
                                ProbBandicVec = setNames(c(1,1,1),c("AC>A","AB>A","BC>B")),
                                modeProbVec = c(1-i/100,i/100,0), # LeftBias Opitmal Explorer
                                timePerBandit = setNames(c(10,10,10,10,10,10),c("AC>A","AC>C","AB>A","AB>B","BC>B","BC>C")),
                                RewardProbPerStation = setNames(c(1,0.5,0.25),c("A","B","C")))
        syntheticExperimentsTemp[[j]] <- mouseExpStats(temp[[1]],temp[[2]],paste0("Synthetic Experiment ",i)) %>% unname()
    }
    # create a dataframe from the list of vectors and compute the column means, then add that to the list of experiments
    syntheticExperimentsOptimal[[i]] <- do.call(rbind.data.frame, syntheticExperimentsTemp) %>% colMeans(na.rm=FALSE) %>% unlist()
}
# Create a dataframe from the list of experiments
syntheticExperimentsOptimalDF <- do.call(rbind.data.frame, syntheticExperimentsOptimal) %>% readr::type_convert()
colnames(syntheticExperimentsOptimalDF) <- names(syntheticStats1)


```



```{r test stats functions}
 # Plot some of the results from the synthetic experiments
 # Plot overlapped line plots for leftBias and probOfCircle
syntheticExperimentsLeftBiasDF$leftBiasReal <- (1:100)/100
syntheticExperimentsOptimalDF$OptimalStrategy <- (1:100)/100
leftBiasPlot <- ggplot(syntheticExperimentsLeftBiasDF, aes(x=leftBiasReal)) + 
                    geom_line(aes(y = ProbOfCircle, color = "Probility Of Circle")) +
                    geom_line(aes(y = leftBias, color = "Left Bias")) + 
                    geom_line(aes(y = RewardProb, color = "Probability of Getting Reward")) +
                    geom_line(aes(y = probDirectionChanges, color = "Probility of Direction Change")) +
                    geom_line(aes(y = `banditChoiceProb_0.25>1`, color = "Probility 0.25>1")) +
                    geom_line(aes(y = `banditChoiceProb_0.5>1`, color = "Probility 0.5>1")) +
                    geom_line(aes(y = `banditChoiceProb_1>0.5`, color = "Probility 1>0.5")) +
                    geom_line(aes(y = `ProbOfChoosing_1`, color = "Probility of choosing 1")) +
                    geom_line(aes(y = `ProbOfChoosing_0.5`, color = "Probility of choosing 0.5")) +
                    geom_line(aes(y = `ProbOfChoosing_0.25`, color = "Probility of choosing 0.25")) +
                    labs(x = "Simulated Left Bias (Sanity Check)", y = "Probability") +
                    theme_classic() + 
                    scale_color_discrete(name = "Statistic")


OptimalStratPlot <- ggplot(syntheticExperimentsOptimalDF, aes(x=OptimalStrategy)) + 
                    geom_line(aes(y = ProbOfCircle, color = "Probility Of Circle")) +
                    geom_line(aes(y = leftBias, color = "Left Bias")) + 
                    geom_line(aes(y = RewardProb, color = "Probability of Getting Reward")) +
                    geom_line(aes(y = probDirectionChanges, color = "Probility of Direction Change")) +
                    geom_line(aes(y = `banditChoiceProb_0.25>1`, color = "Probility of 0.25>1")) +
                    geom_line(aes(y = `banditChoiceProb_0.5>1`, color = "Probility of 0.5>1")) +
                    geom_line(aes(y = `banditChoiceProb_1>0.5`, color = "Probility of 1>0.5")) +
                    geom_line(aes(y = `ProbOfChoosing_1`, color = "Probility of choosing 1")) +
                    geom_line(aes(y = `ProbOfChoosing_0.5`, color = "Probility of choosing 0.5")) +
                    geom_line(aes(y = `ProbOfChoosing_0.25`, color = "Probility of choosing 0.25")) +
                    labs(x = "Probility Of Choosing Best Strat", y = "Probability") +
                    theme_classic() + 
                    scale_color_discrete(name = "Statistic")

ggplot2::ggsave(paste0("./plots/OptimalStratPlot.pdf"),device = "pdf",OptimalStratPlot)
ggplot2::ggsave(paste0("./plots/leftBiasPlot.pdf"),device = "pdf",leftBiasPlot)

cowplot::plot_grid(leftBiasPlot, OptimalStratPlot, nrow = 2)

```
  

```{r read data loop}
# Set the path to the hdf5 file
datafile <- '/home/gummi/banditExperiment/dataset.data'

# Load the hdf5 file
data <- h5dump(datafile,load=TRUE)

# Compute experiment stats
experimentData <- tabulateExperiments(data,datafile,2)

```


```{r explore data}
# Use the features that Alex asked for
TesmerFeatures <- c("ProbOfChoosing_0.25",
                  "ProbOfChoosing_0.5",
                  "ProbOfChoosing_1",
                  "banditChoiceProb_0.25>1",
                  "banditChoiceProb_1>0.5",
                  "banditChoiceProb_0.5>1",
                  "numberOfTrials",
                  "ProbOfCircle")

# Generate plots for whole probabalistic part
plotPCAMouse(experimentData[["ProbExperimentsProbPart"]],
            TesmerFeatures,
            "SelectFeatures_EntireProbPart",
            4,
            0.8,
            TRUE)

# Generate plots for replicate collapsed whole probabalistic part
plotPCAMouse(averageReplicates(experimentData[["ProbExperimentsProbPart"]]),
            TesmerFeatures,
            "SelectFeatures_ReplicateCollapsedProbPart",
            3,
            0.9,
            FALSE)


# Generate plots for second half of probabalistic part
plotPCAMouse(experimentData[["SplitProbExperiments"]][["Split_1050_1800"]],
            TesmerFeatures,
            "SelectFeatures_SecondHalfProbPart",
            4,
            0.8,
            TRUE)

# Generate plots for replicate collapsed second half of probabalistic part
plotPCAMouse(averageReplicates(experimentData[["SplitProbExperiments"]][["Split_1050_1800"]]),
            TesmerFeatures,
            "SelectFeatures_ReplicateCollapsedSecondHalfProbPart",
            4,
            0.7,
            FALSE)

# Get the numeric columns of the data
numericColumns <- sapply(experimentData[["ProbExperimentsProbPart"]],is.numeric)

# Generate plots probabalistic part with all features that are numeric
plotPCAMouse(experimentData[["ProbExperimentsProbPart"]],
            names(numericColumns)[numericColumns][-1],
            "AllFeatures_EntireProbPart",
            4,
            0.4,
            FALSE)

# Generate plots for replicate collapsed probabalistic part with all features that are numeric
plotPCAMouse(averageReplicates(experimentData[["SplitProbExperiments"]][["Split_1050_1800"]]),
            names(numericColumns)[numericColumns][-1],
            "AllFeatures_SecondHalfProbPart",
            4,
            0.4,
            FALSE)

# Generate plots for replicate collapsed probabalistic part with all features that are numeric
plotPCAMouse(averageReplicates(experimentData[["ProbExperimentsProbPart"]]),
            names(numericColumns)[numericColumns][-1],
            "AllFeatures_ReplicateCollapsedProbPart",
            4,
            0.4,
            FALSE)

# Generate plots for replicate collapsed probabalistic part with all features that are numeric

# Filter out for only fasted mice
averageReplicates(experimentData[["SplitProbExperiments"]][["Split_1050_1800"]]) %>%
            filter(State == "Fasted") -> SecondHalfCollapsedFastedOnly

plotPCAMouse(SecondHalfCollapsedFastedOnly,
            TesmerFeatures,
            "SelectFeatures_SecondHalfProbPart_FastedOnly",
            4,
            0.4,
            FALSE)


```



```{r plot some stuff}

DetData <- experimentData[["DetExperiments"]]      

# Plot left choice probability boxplot fill by sex and faceted by state
ggplot(DetData, aes(x = Sex,y=as.numeric(leftBias),fill=Sex)) + 
        geom_boxplot() + 
        theme_classic() +
        labs(y = "Left Choice Probability",title = "Directional Bias") +
        facet_wrap(.~State) 

# Plot left choice probability boxplot fill by state and faceted by mouse
ggplot(DetData, aes(x = as.factor(Mouse),y=as.numeric(leftBias),fill=Sex)) + 
        geom_boxplot() + 
        theme_classic() +
        labs(y = "Left Choice Probability",title = "Directional Bias",x="Mouse")

# Create a pivot of the pumb bias
DetData %>%
        dplyr::select(Mouse,
                      State,
                      Sex,
                      ProbOfChoosing_A,
                      ProbOfChoosing_B,
                      ProbOfChoosing_C) %>%
        tidyr::pivot_longer(cols = c("ProbOfChoosing_A",
                                     "ProbOfChoosing_B",
                                     "ProbOfChoosing_C"),
                            names_to = "Pump",
                            values_to = "Prob") %>%
ggplot(aes(x = Pump,y=as.numeric(Prob),fill=Pump)) + 
        geom_boxplot() + 
        theme_classic() +
        geom_hline(yintercept = 0.33,linetype="dashed") 
        #facet_wrap(.~Mouse)



```


