---
title: "Untitled"
output: github_document
---

```{r }

library(readxl)
library(purrr)
library(stringr)
library(dplyr)

# Define the folder path
folder_path <- "/home/gummi/banditExperiment/AllEXCELS"

# Get the list of all .xlsx files in the folder
file_list <- list.files(path = folder_path, pattern = "*.xlsx", full.names = TRUE)

# Define a function to read a specific cell from an xlsx file
read_cell <- function(file_path, row, col) {
  sheet <- read_excel(file_path, col_names = FALSE,progress = FALSE)
  splitt <- str_split(as.character(sheet[row, col]), "\\\\", simplify = TRUE)
  file_name <- splitt[length(splitt)]
  file_name <- str_remove(file_name, ".avi")
  return(file_name)
}

# Define a function to extract information from the file name
extract_info <- function(file_path) {
  file_name <- str_remove(file_path, paste0(folder_path, "/"))
  file_name <- str_remove(file_name, ".xlsx")
  parts <- str_split(file_name, "-", simplify = TRUE)
  return(parts[c(2, 3)])
}

# Apply the functions to each file
results <- map_df(file_list, ~ {
  file_id <- read_cell(.x, row = 19, col = 2)
  info <- extract_info(.x)
  data_frame(
    `Header String` = file_id,
    `Experiment Name` = info[1],
    `Trial Number` = as.numeric(str_remove(info[2], "Trial\\s*"))
  )
})

# Print the results
print(head(results))


```


```{r }

stats <- list()
for (file in list.files("/home/gummi/banditExperiment/ALLSTATS",full.names = TRUE) ){
    file_name <- str_remove(file, ".xlsx")
    parts <- str_split(file_name, "-", simplify = TRUE)
    sheet <- read_excel(file, col_names = FALSE,progress = FALSE)
    sheet$`Experiment Name` <- parts[2]
    sheet <- mutate(sheet,`Trial Number` = as.numeric(str_remove(`...1`, "Trial\\s*")))
    sheet <- sheet[,-1]
    sheet <- sheet[-1,]
    stats[[file]] <- sheet
    print(file)
}

allStats <- do.call(rbind, stats)

colnames(allStats) <- c("Distance moved Center-point Total cm",	"Velocity Center-point Mean cm/s", "Experiment Name" ,"Trial Number")

# LEFT Join allStats to results BY Experiment Name and Trial Number
final <- left_join(allStats,results, by = c("Experiment Name", "Trial Number"))

final <- final[,c(1,2,5)]

# Save inal as csv
write.csv(final, file = "final2.csv", row.names = FALSE)

```


