---
title: "Bandit Analysis"
output: github_document
---

Read in the data and store it as a data frame

```{r setup, include=FALSE}

library(rhdf5)
library(tidyverse)
library(ggplot2)

```


```{r helper functions}
# Load helper functions
source("banditAnalysis.r")
source("banditDataProcessing.r")
source("banditArchetypalAnalysis.r")

```


```{r read data loop}
# Set the path to the hdf5 file
datafile <- '/home/gummi/banditExperiment/data/dataset08212023.data'

# Load the hdf5 file
data <- h5dump(datafile,load=TRUE)

# Compute experiment stats
experimentData <- tabulateExperiments(data,datafile,2,'/home/gummi/banditExperiment/RawTelemteryData')
# Save experment Data

save(experimentData,file=paste0("experimentData_",str_remove_all(Sys.Date(), "-"),".RData"))
#load(paste0("experimentData_",str_remove_all(Sys.Date(), "-"),".RData"))



```


```{r general data analysis}


# Designate the variables of interest from the data set
FeaturesOfIntrest <- c("P(0.25)",
                    "P(0.5)",
                    "P(1)",
                    "P(0.25->1)",
                    "P(1->0.5)",
                    "P(0.5->1)",
                    "P(Circle)")


# Retrieve the data set of interest
dataset <- experimentData[["SplitProbExperiments"]][["Split_1050_1800"]] #"Split_1050_1800"  "Split_1300_1800"

# Process the data set
dataset$Mouse <- as.character(dataset$Mouse)

colnames(dataset)[52] <- "RewardEvennes"

dataset$RewardEvennes <- as.numeric(dataset$RewardEvennes)

# Filter out any mice that have no trials (one drunk mice seems to have no trial past 5 minutes lol)
dataset <- dataset %>%
            filter(`NTrials` > 5)

dataset <-  dataset %>%
                 averageReplicates()

# Change States to consider name DTR+ as separate state  (DTRplus cuz some metaprogramming fucntionality is not working with the + sign)
dataset <- mutate(dataset, State = ifelse(MouseType == "DTR+", paste0(State,"DTRplus"), State))

# Filter Out GCAMP
dataset <- dataset %>%
            filter(MouseType != "GCAMP")

# Take only States that we are interested in (I think were completely dropping fed mice)
dataset <- dataset %>%
            filter(State %in% c("FastedEthDTRplus","FastedEth2DTRplus","FastedSalDTRplus",
                                "FastedVehDTRplus","FastedAlm","FastedEth",
                                "FastedEth2","FastedSal","FastedSnap","FastedVeh","Fasted"))




plotPCAMouse(dataset,c(FeaturesOfIntrest,"meanTimeToChoice","NTrials"),"LastHalfData",6,0.5,FALSE,c("RewardEvennes"))


```



```{r archtypal analysis plots}




# Define the adjency matrix for the predefined archetypal analysis
archMat3 <- matrix(c(1/3, 1/3, 1/3, 0.5, 0.5, 0.5, 1,  # Circle 
    	            0,   0.5, 0.5, 1,   1,   1,   0,  # GO
                    0.5,   0.5,   0,   0,   1,   0,   0), # Uncertainty seeking (maybe better to change to uncertainty avoiding  0.5,   0,   0.5,   1,   0,   1,   0)
                                                    nrow = 3,
                                                     ncol = 7, 
                                                     byrow = TRUE,
                                                    dimnames = list( c("Circle","GO","Uncertainty"),
                                                    FeaturesOfIntrest))

archMat4 <- matrix(c(1/3, 1/3, 1/3, 0.5, 0.5, 0.5, 1,  # Circle 
    	            0,   0.5, 0.5, 1,   1,   1,   0,  # GO
                    0.5,   0.5,   0,    0,   1,   0,   0, # Uncertainty seeking (maybe better to change to uncertainty avoiding  0.5,   0,   0.5,   1,   0,   1,   0)
                    0.5,   0,     0.5,  1,  0,   0.5,  0), # Certainty Seeking	
                                                    nrow = 4,
                                                     ncol = 7, 
                                                     byrow = TRUE,
                                                    dimnames = list( c("Circle","GO","Uncertainty","Certainty"),	
                                                    FeaturesOfIntrest))

# Designate the pairs of states to contrast in during plotting.
contrastList <- list(c("FastedAlm", "FastedVeh"),
                        c("FastedSnap", "FastedVeh"),
                        c("FastedEth","FastedSal"),
                        c("FastedEth2","FastedSal"),
                        c("FastedEthDTRplus","FastedSalDTRplus"),
                        c("FastedEth2DTRplus","FastedSalDTRplus")) 


# Do classical archetypal analysis (do plotting for 4 archetypes) This will generate some plots
AutoArchAnalysis <- autoArchetypesAnaPlots(dataset,"AutoFourArchetypes",4,c(FeaturesOfIntrest,"NTrials"),contrastList,FALSE) 

# Archatypal analysis with the 3 predefined archetypes
predefArchThree <- ArchAnalysisWithPredefined(archMat3,dataset,squareVec,TRUE,0.001,TRUE,TRUE,FALSE,"PredefThree",FeaturesOfIntrest,contrastList)
predefArchThree[["error"]]
predefThreePlots <- plotArchetypalAnalysisPredefined(TRUE,contrastList,predefArchThree[[1]],"PredefThree",archMat3)

# Archatypal analysis with 4 predefined archetypes
predefArchFour <- ArchAnalysisWithPredefined(archMat4,dataset,squareVec,TRUE,0.001,TRUE,TRUE,FALSE,"PredefFour",FeaturesOfIntrest,contrastList)
predefArchFour[["error"]]
predefFourPlots <- plotArchetypalAnalysisPredefined(FALSE,contrastList,predefArchFour[[1]],"PredefFour",archMat4)




```


```{r archtypal analysis plots}
# Plot pca of archetypes

pcaArchs <- prcomp(predefArchFour[[1]][,1:4],center = TRUE,scale. = TRUE)

ggplot(cbind(pcaArchs$x,predefArchFour[[1]][,6:8]),aes(x = PC1, y = PC2, color = State)) +
        geom_point() +
        theme_bw() + 
        guides(color = guide_legend(override.aes = list(label = NULL)))


```

```{r generate plots}

# Create a function for plotting scatterplots with corr 

scatterWrapper <- function(archData,archtypesNames,variableOFInterest,name) {
    tempDF <- pivot_longer(archData,cols = archtypesNames,names_to = "Archs",values_to = "Value")
    plot <- ggpubr::ggscatter(tempDF,x = "Value", y = variableOFInterest,add = "reg.line",conf.int = T,cor.coef = T) +
            facet_grid(State~Archs ,scales = "free_x") +
            ggtitle(name) + 
            theme_bw() 

    return(plot)
}

dataArchComb <- cbind(predefArchFour[[1]],dataset)

scatterWrapper(dataArchComb,c("Circle","Certainty","Uncertainty","GO"),"rewardPerDistance", "Reward per Distance")

scatterWrapper(dataArchComb,c("P(0.25)","P(0.5)","P(1)","P(Circle)","P(DirectionChange)"),"rewardPerDistance", "Reward per Distance")

scatterWrapper(dataArchComb,c("Circle","Certainty","Uncertainty","GO"),"totalDistance", "Total Distance")

scatterWrapper(dataArchComb,c("P(0.25)","P(0.5)","P(1)","P(Circle)"),"totalDistance", "Total Distance")

scatterWrapper(dataArchComb,c("Circle","Certainty","Uncertainty","GO"),"RewardEvennes", "Reward Evennes")



scatterWrapper(dataArchComb,c("Circle","Certainty","Uncertainty","GO"),"meanTimeToChoice", "Mean time to choice")

ggpubr::ggscatter(dataset,x = "NTrials", y = "totalDistance",add = "reg.line",conf.int = T,cor.coef = T)

group_by(duplicated(dataArchComb),State) %>% select(meanTimeToChoice)%>% summarise(mean())

reps<- predefFourPlots[["representations"]]

tempDF <- reps[[3]]

tempDF$rewardPerDistance <- dataset$rewardPerDistance
	
ggplot() +
        geom_point(data = tempDF,aes(x = PC1, y = PC2, color =dataset$rewardPerDistance)) +
        scale_color_gradient(low = "lightgray", high = "red") +
        geom_text(data = reps[[4]],aes(x = PC1, y = PC2, label = Archs)) + 
        theme_bw() + 
        guides(color = guide_legend(override.aes = list(label = NULL))) 





```

 




```{r helper functions}
# Load helper functions
source("banditAnalysis.r")
source("banditDataProcessing.r")
source("banditArchetypalAnalysis.r")

```

```{r addd}

t.test(Circle ~ State,data = dataArchComb[which(dataArchComb$State %in% c("FastedVeh","FastedAlm")),])
t.test(GO ~ State,data = dataArchComb[which(dataArchComb$State %in% c("FastedVeh","FastedAlm")),])
t.test(Uncertainty ~ State,data = dataArchComb[which(dataArchComb$State %in% c("FastedVeh","FastedAlm")),])
t.test(Certainty ~ State,data = dataArchComb[which(dataArchComb$State %in% c("FastedVeh","FastedAlm")),])


```
